### ISSUE TITLE
FilterDropDownMenue modifizieren

### ISSUE THREAD

**Issue by kerstin-m** [danielkull/capp#100]

**Comment by kerstin-m** [comment]
- [ ] trunkSizes in einem int (min und max) angeben, damit sie mit der Datenbank abgeglichen werden können
- [ ] Features aus der Datenbank-Tabelle laden

**Comment by kiraGit67** [comment]
Mir ist auch aufgefallen, dass die Beschriftung der trunkSizes sich teilweise überschneidet, andererseits Lücken lässt:

- [ ] S - 170-250 Liter
- [ ] M - 350-500 Liter
- [ ] L - 450-550 Liter
- [ ] XL - 380-800 Liter
- [ ] XXL - bis zu 1600 Liter

Ich denke, es ist besser die einzelnen Größen nahtlos aneinander anschließen zu lassen: 
- [ ] S - 170-250 Liter
- [ ] M - 251-450 Liter
- [ ] L - 451-550 Liter
- [ ] XL - 551-800 Liter
- [ ] XXL - 801-1600 Liter

**Comment by kiraGit67** [comment]
Die Features können auch aus der features Tabelle aus unserer Datenbank ausgelesen werden:
methods: {
    async getFeatures(){
        const { data } = await supabase.from("features").select();
        this.features = data;
        console.log(this.features)
    }
}, 
mounted(){
    this.getFeatures();
}

**Comment by kiraGit67** [comment]
Die Änderungen an der Filter DropDown Menue Komponente gelten auch für die User Question Menue Komponente, da ja beide auf den selben Kriterien basieren. Das Filter DropDown Menu wurde ja aus dem User Question Menue abgeleitet.
