### ISSUE TITLE
Projekt Ideen

### ISSUE THREAD

**Issue by danielkull** [danielkull/capp#113]
Punkte die wir nicht vergessen sollten und die zu besprechen sind:

- Log Out Button Komponente erstellen (Ohne Funktion) (Nur im Persönlichen View austesten) (Designe steht noch nicht fest)

- Settings Komponente erstellen (Ohne Funktion) (Nur im Persönlichen View austesten) (Designe steht noch nicht fest)
  - Platzhalter (Benutzt unsere vorhanden Komponenten wie Akkordion wenn möglich) wie:
  - Darkmode
  
- Profil Komponente erstellen (Ohne Funktion) (Nur im Persönlichen View austesten) (Designe steht noch nicht fest)
  - Platzhalter (Benutzt unsere vorhanden Komponenten wie Akkordion wenn möglich) wie:
  - Change of:
    - All Userdata (Username, Mail, Adresse, ect.)

- FAQ Komponente erstellen (Ohne Funktion) (Nur im Persönlichen View austesten) (Designe steht noch nicht fest)
  - Hier ein leeres Akkordion (Im Besten Fall ist es im Leeren Zustand überall einsetzbar.
  - Die Akkordion Komponente solte am besten mit Slots/Props etc. variable einstellbar sein, damit der Inhalt relative leicht angepasst wird ohne die Grund Akkordion Komponente zu verändern.

- Platzhalter Messenger Bereich (Dazu auch eine eigne Komponente erstellen)

**Comment by StefanH87** [comment]
- neben profilkomponente, die Fahrzeughalter komponente mit den wichtigstens Daten zum Autobesitzer ( Versicherungsnummer, etc)

- den Kalender nur als Verweis im Userprofil
