### ISSUE TITLE
Fehlermeldung Filterliste

### ISSUE THREAD

**Issue by StefanH87** [danielkull/capp#122]
![Image](https://user-images.githubusercontent.com/120994075/252056404-a653bcfe-5c10-402a-906c-3b69c0ee904a.png)

**Comment by kiraGit67** [comment]
Tritt diese Fehlermeldung bei der Fragebogen-Komponente auch auf? Da habe ich die Variable carFeaturesFromDB in der Funktion getFeatures() genauso gehandhabt... 
carFeaturesFromDB habe ich als const definiert, da könnte der Fehler liegen... Wahrscheinlich muss sie als let definiert werden. 
Lass uns mal morgen gemeinsam drüber schauen...
![Bildschirmfoto 2023-07-09 um 23 04 45](https://github.com/danielkull/capp/assets/122105147/dfef7002-65fe-4b0c-a431-dbc0cee20948)
![Bildschirmfoto 2023-07-09 um 23 05 04](https://github.com/danielkull/capp/assets/122105147/73933aa4-7e73-4d04-b442-0d5c734f617b)
