### ISSUE TITLE
CSS :disabled Pseudoclass?

### ISSUE THREAD

**Issue by danielkull** [danielkull/capp#124]
### Zum Besprechen:

Evtl. ein neues Issue:

- Brauchen wir ein :disabled zustand für unsere Button Komponente? Also für alle Elemente mit den wir in der App interagieren?
- Beim Log in oder Sign In z.B. könnte man das machen, damit man den Button nur einmal drückt und das Form mit den Fetch Request nur einmal abgeschickt wird.
- Zudem gibt es noch die Möglichkeit das wir bei einem Preview Modus alle Elemente die der nicht angemeldet Nutzer nicht benutzen kann einfach auf :disabled setzen in dem Fall das niemand angemeldet ist.
- @StefanH87 : Falls wir uns hierfür entscheiden bräuchten wir im CSS dafür etwas das alles auf Grau oder so stellt (oder den Button eingedrückt erscheine lässt...)

**Comment by StefanH87** [comment]
-idee finde ich gut für den Fall das ein suer noch kein auto angegegben hat oder eben der Sign In noch nicht abgeschlossen ist
- mit CSS lässt sich einfach ne Klasee erstellen wo wir den style ändern und mit " pointer-events: none; " ist er nicht mehr anwählbar
- oder qals atrribut disabled setzen
- kann in der Button Komponente so neKlasse einbauen

**Comment by StefanH87** [comment]
- wurde erstellt

**Comment by danielkull** [comment]
Danke, habe den Pull Request gemerged.
Würde hier noch eine Diskussion machen, bzgl. ob wir die classe nicht als Pseudo-classe darstellen. also statt .disabled --> .Log-btn:disabled. Das lässt sich dann relative leicht mit true or false anfragen vom JS verbinden. 
Und ob wir beim cursor: none bleiben wollen oder es mit cursor: not-allowed; klarer Zeigen wollen.
Mit der pseudoclasse :disabled wäre dann auch die funktion des cursor: none erfüllt, wie du bereits geschrieben hast.

**Comment by StefanH87** [comment]
ja können wir anpassen - an die Pseudoklasse hat ich grad garnicht gedacht
