### ISSUE TITLE
CleanUp LogView.vue

### ISSUE THREAD

**Issue by kerstin-m** [danielkull/capp#130]
bitte löschen
Zeile 380 -382

**Comment by StefanH87** [comment]
![image](https://github.com/danielkull/capp/assets/120994075/01710294-0b32-4104-a9f2-e3e41c18500f)

Zeilen wurden gelöscht

![image](https://github.com/danielkull/capp/assets/120994075/7a62d6df-1d1c-41f4-a8a6-f9f370053065)
