### ISSUE TITLE
create car-card / User Profile

### ISSUE THREAD

**Issue by StefanH87** [danielkull/capp#14]
- [x] create componente
- [x] create User Profile View - Mobile First
- [ ]

**Comment by danielkull** [comment]
Jetziger Stand:


![Image](https://github.com/danielkull/capp/assets/119632155/1aee9861-8474-4d95-a423-3c97c5aa4417)

**Comment by danielkull** [comment]
- [ ] Der Router Pfad muss noch angepasst werden. Jetziger Stand /userProfil --> sollte zu --> /UserProfileView

Beispiel:
```js
<router-link to="/UserProfileView">Userprofile</router-link>
```
