### ISSUE TITLE
create Nav Bar

### ISSUE THREAD

**Issue by StefanH87** [danielkull/capp#15]
- [x] create componente
- [x] Mobile First
- [x] Drop Down 
- [x] Menue Liste

**Comment by danielkull** [comment]
In etwa so?



![Image](https://github.com/danielkull/capp/assets/119632155/f3c27b10-ed1c-46d3-b89b-b6d43b2cda83)



![Image](https://github.com/danielkull/capp/assets/119632155/68205f49-aeae-4861-ab88-a0b770aafecb)
