### ISSUE TITLE
Warum funktionieren die icons nicht mehr?

### ISSUE THREAD

**Issue by kerstin-m** [danielkull/capp#150]
- Customer properties in color-properties css definiert als rgba, als Werte aber nur drei angegeben (Zeile 49)
- --svg-width nicht in den Cusotomer propertes definiert, sondern nur in den einzelnen vues.

**Comment by kiraGit67** [comment]
--svg-width ist in den custom css style Dateien nicht definiert.
![Bildschirmfoto 2023-07-11 um 11 13 38](https://github.com/danielkull/capp/assets/122105147/9a3055ab-ef44-475e-b284-52e95ab0ea1f)
