### ISSUE TITLE
"Weitere Angaben" mit Tabelle verknüpfen

### ISSUE THREAD

**Issue by kerstin-m** [danielkull/capp#159]
Kirsten zieht hieraus den Branch, um ihre Tabelle unter "Weitere Angaben" zu verknüpfen siehe https://github.com/danielkull/capp/pull/156

**Comment by StefanH87** [comment]
ich habe das feld freigelassen damit sie driekt ihre Tabelle einfügen kann um es ihr leichter zumachen
- nur falls sie sich wundert das nichts drin ist
