### ISSUE TITLE
RadioButton.vue

### ISSUE THREAD

**Issue by kerstin-m** [danielkull/capp#197]
Ist das noch ein issue oder ein cleanup?

![Image](https://user-images.githubusercontent.com/120080320/253787314-94770885-cfef-4b9d-884f-ba111533a1bf.png)

**Comment by danielkull** [comment]
Die Komponente müsste eigentlich noch fertiggestellt werden. Bisher wurden glaube ich alle Radio Elemente einzeln geschrieben und beziehen sich nicht auf die Komponente oder?
Ich meine wenn die Datenanbindung zu dem Store --> Supabase passt dann brauchen wir auch hier nichts zu machen bis zur Abgabe. Wenn die Daten aber nicht weitergeleitet werden oder es an vielen verschiedenen stellen immer wieder aufkommt, dann wäre es Sinnvoll die Komponente als Issue fertigzustellen.
