### ISSUE TITLE
Superbase

### ISSUE THREAD

**Issue by kerstin-m** [danielkull/capp#2]
db Diagramm https://dbdiagram.io/d/6491c1d202bd1c4a5ec8aeec  in Superbase umwandeln

**Comment by kiraGit67** [comment]
- [ ] db Diagramm https://dbdiagram.io/d/6491c1d202bd1c4a5ec8aeec in postgre sql exportieren

**Comment by kiraGit67** [comment]
Supabase Anwendung installiert und konfiguriert
Supabase Beispiel erstellt für die Einbindung von 
Auto-Marken (brands Tabelle)
Auto-Typen (car_types Tabelle in Verbindung mit brands Tabelle)
Autos (cars Tabelle in Verbindung mit cars_features Tabelle)
User (users Tabelle)

**Comment by danielkull** [comment]
Das Problem könnte darin liegen das wir in der createClient() wenn wir die Keys/URL abfragen nicht mit process.env die Daten auslesen.

**Comment by danielkull** [comment]
Branch wurde gelöscht und nochmal neu hochgeladen
