### ISSUE TITLE
Bug Fixen in MainPage

### ISSUE THREAD

**Issue by danielkull** [danielkull/capp#209]
In MainPage gibt es folgende Bugs/Fehler die gefixed werden müssten:

![Image](https://github.com/danielkull/capp/assets/119632155/6f899e8d-8498-47a4-9534-bdded3ba83b9)

![Image](https://github.com/danielkull/capp/assets/119632155/ff76ad53-5763-422e-9e62-25ed25b51e2c)

**Comment by StefanH87** [comment]
wurde im isssue 287 geschlossen
