### ISSUE TITLE
create log in page

### ISSUE THREAD

**Issue by StefanH87** [danielkull/capp#23]
- [x] create vue
- [x] create html structure
- [x] create css

**Comment by danielkull** [comment]
Idee von Stefan Preview Butten um einen Einblick in die App zu bekommen ohne Funktionalität die der Log in Bringt

**Comment by danielkull** [comment]
Alle issues wurden umgesetzt.
Infos: Navbar hat nun Display: none und kann bei bedarf an und ausgeschalten werden

**Comment by danielkull** [comment]
Sehr schön 😊, gefällt mir sehr gut wie es umgesetzt wurde.
Freu mich immer über die Animationen 😁

Pull request wurde von mir gereviewd.
Notes:

1. Navbar hat nun Display: None. (An alle bitte beachten das kann man im Browser Entwicklungsmodus an und ausschalten
2. Beim Skalieren der Seite hat man noch diesen Grünen Balken, der Auftraucht (Kann in Zukünftigen Issue erledigt werden)
3. Beim rechten Log In Beispiel mit den Input Feldern ist ein Button mit einem Pfeil. Beim Hovern bekommt er eine Animation die noch etwas buggy ist. Wenn man sich langsam auf den Pfeil zubewegt, dann gibt es eine ziemliche Wackel Animation (Ebenfalls zukünftiges Issue.
4. Merge Konflikt entdeckt beim Router und der Navbar (Das kommt vor wenn wir neue Views registrieren). Habe diesen gelöst und die Fehlenden Zeichen eingefügt (Das Objekt literal "{ }," hat es durch den Merge Konflikt zerschossen).

Da ich durch den Merge Konflikt eine Änderung durchgeführt habe, bin ich nicht mehr Reviewer. Bitte jemand anderes den finalen Review durchführen und  mergen. Danke 🙏
