### ISSUE TITLE
car_types Tabelle in car_models umbenennen

### ISSUE THREAD

**Issue by kerstin-m** [danielkull/capp#24]
- [ ] Umbenennung von car_types in car_models
- [ ] type_id in der cars Tabelle umbenennen in model_id

**Comment by kerstin-m** [comment]
@kiraGit67 Das hast Du doch schon längst erledigt, oder?

**Comment by kiraGit67** [comment]
Postgre SQL Syntax, um eine Tabelle umzubenennen:

- [ ] ALTER TABLE table_name RENAME TO new_table_name;
- [ ] In unserem Fall: ALTER TABLE car_types RENAME TO car_models

**Comment by kiraGit67** [comment]
Vielleicht könnten wir den Namen der Tabelle car_types belassen - und das zusätzliche enum-Feld in der cars Tabelle vielleicht kind_of_car (Art von Auto) nennen? Dann könnten wir uns die ganze nicht ganz unverfängliche Prozedur mit der Tabellen-Umbenennung sparen - und Nerven auch...
