### ISSUE TITLE
im car-profil-view einen back button einfuegen

### ISSUE THREAD

**Issue by danielkull** [danielkull/capp#240]
- [ ] Back Button einfügen und den router zur main zurück schicken.

**Comment by kiraGit67** [comment]
In welche Komponente oder View (Datei) muss der Back-Button denn eingefügt werden?

**Comment by danielkull** [comment]
Car-Profile View. Sehe aber gerade das diese Issue zweimal existiert #248 . Schließe daher dieses hier.
