### ISSUE TITLE
ungenutzte Klassen und HTML-Tags sammeln

### ISSUE THREAD

**Issue by kerstin-m** [danielkull/capp#254]
Extension CSS Peek

**Comment by kerstin-m** [comment]
Nicht mit Str Shift F gefunden
color-properties.css
--sur-hover Z. 23
--clr-seat-act Z. 36
--icon-clr Z. 84
--state-red Z.189

**Comment by kerstin-m** [comment]
Nicht mit Str Shift F gefunden
global.css
--clr-seat-icon Z. 89
--clr-state-active
--btn-height-small Z.137

**Comment by kerstin-m** [comment]
reset.css
applet
iframe
h6
blockquote
acronym
big
cite
code
del
em
dfn
ins
kbd
samp,
small,
strike,
strong,
sub,
sup,
tt,
var,
ol
fieldset
legend
caption
tfoot
aside
canvas
details
embed
figcaption
hgroup
menu
output
ruby
summary
mark
audio,
video

**Comment by StefanH87** [comment]
erleedigt
