### ISSUE TITLE
Warnungen Auto-Bilder

### ISSUE THREAD

**Issue by kerstin-m** [danielkull/capp#284]

**Comment by kerstin-m** [comment]
![Image](https://github.com/danielkull/capp/assets/120080320/4603e08f-4b56-47a4-91d1-399bd4e67539)

**Comment by danielkull** [comment]
Ja, es scheint das unsere Bilder die wir per http laden, doch nicht so sauber sind. Im Moment existieren nur drei die sauber geladen werden und die sind direkt https links von pexels...

**Comment by danielkull** [comment]
Okay, also die Bilder werden nur Anzeigt wenn man Gleichzeitig bei seinem VSCode den Server laufen lässt. Sobald dieser nicht mehr aktiv ist, kann man bei Netlify auch nicht mehr die Bilder bekommen.
