### ISSUE TITLE
Hilfstexte bei Fragebögen anpassen

### ISSUE THREAD

**Issue by kerstin-m** [danielkull/capp#296]

**Comment by kerstin-m** [comment]
![Image](https://github.com/danielkull/capp/assets/120080320/5c703546-d118-4ca4-b04d-1028f4872ebb)

**Comment by StefanH87** [comment]
bei mir sieht es normal aus

![image](https://github.com/danielkull/capp/assets/120994075/edd33712-d180-4c1a-9c8f-3ac04ef222dc)

**Comment by StefanH87** [comment]
glaube der screenshot von kerstin ist noch vpr dem merge
- hier ist der hintergrund noch anders

**Comment by StefanH87** [comment]
- active state bearbeitet für den font und den hintergund
- 
![image](https://github.com/danielkull/capp/assets/120994075/bb634408-be56-4c47-8aac-2313fd4aab50)

**Comment by StefanH87** [comment]
-Footer in der desktopn version angepasst

**Comment by StefanH87** [comment]
gelöst
