### ISSUE TITLE
Vue Router installieren

### ISSUE THREAD

**Issue by kiraGit67** [danielkull/capp#3]
Install Vue Router
- [x] https://router.vuejs.org/installation.html
- [x] npm install vue-router@4

Generate different Views
- [ ] CarsView
- [ ] SingleCarView
- [ ] CarTypesView
- [ ] CarBrandsView
- [ ] UsersView
- [ ] UserLoginView
- [ ] UserRegisterView

**Comment by volkanfilazi** [comment]
Hello :) Do you need help with router or did you write a task for yourself?

**Comment by danielkull** [comment]
Hi @volkanfilazi ,
thanks for asking. For now it's only a tasklist for us, as we are trying to create a car sharing app. Thats kind of our final project in our cooding-bootcamp.
But most likely, we will have tons of questions in the furture 😅

**Comment by danielkull** [comment]
Würde hier erstmal nur den Router installieren. Und die Grundstruktur aufbauen. Die einzelnen spezifischen Views können wir dann in separate Issues packen. Die sich auch mit dem Inhalt der View beschäftigen.
Das folgende Grundgerüst ist auch nur ein Beispiel und wir verändern das später. Wir können dann aber auf unterschiedlichen Views Arbeiten ohne uns in die quere zu kommen bei der HelloWorld Komponente oder der App.vue Datei.
Was wir benötigen nach der Installation ist:

- [ ] Erstelle einen neuen Ordner "router"in src/
- [ ] Erstelle in den Ordner index.js
- [ ] Füge folgenden Code ein
```javascript
import { createRouter, createWebHistory } from 'vue-router'
import HomeView from "../views/HomeView.vue";

const routes = [
    {
        path: "/",
        name: "home",
        component: HomeView,
    },
    {
        path: "/about",
        name: "about",
        component: () => import(/* webpackChunkName: "about" */ "../views/AboutView.vue"),
    },
];

const router = createRouter({
    history: createWebHistory(),
    routes,
});

export default router;
``` 

- [ ] Erstelle einen neuen Ordner "views"in src/
- [ ] Lege eine Datei "HomeView.vue mit folgendem Beispielinhalt an
```javascript
<template>
  <div>
    <h1>Test von Home View</h1>
  </div>
</template>

<script>
export default {};
</script>

<style scoped></style>
``` 
- [ ] Lege eine Datei "AboutView.vue mit folgendem Beispielinhalt an
```javascript
<template>
  <div>
    <h1>Test von About View</h1>
  </div>
</template>

<script>
export default {};
</script>

<style scoped></style>
``` 

- [ ]  Editiere die main.js im src/ Order (Importiere router und rufe diese bei createApp(...)... auf
```javascript
import router from "./router";

createApp(App).use(router).mount("#app");
``` 

- [ ] Editiere die App.vue unter dem src/ Ordner (Füge über der <HelloWorld /> Componente folgendes ein)
```javascript
<nav>
    <router-link to="/">Home</router-link> |
    <router-link to="/about">About</router-link>
  </nav>
  <router-view />
```
