### ISSUE TITLE
Ergänzung Fragebogen

### ISSUE THREAD

**Issue by StefanH87** [danielkull/capp#30]
In den ersten Reiter zum "Angaben zum fahrzeug"

- [ ] neue UL mit Überschrift "Raucher" + 2 Li Elementen - Ja oder Nein - RAdiobuttons
- [ ] neue UL mit Überschrift "Isofix" + 2 Li Elementen - Ja oder Nein - RAdiobuttons

![Image](https://user-images.githubusercontent.com/120994075/249048620-5e708369-513c-4964-895d-4523738c3282.png)

**Comment by kerstin-m** [comment]
@ Stefan:   neue UL mit Überschrift "Isofix" + 2 Li Elementen - Ja oder Nein - RAdiobuttons: Ist der Punkt so noch aktuell? Ich habe den Punkt Isofix als Unterpukt von Kindersitz genommen, siehe
