### ISSUE TITLE
Liste Fragebogen Vermieter

### ISSUE THREAD

**Issue by kerstin-m** [danielkull/capp#33]
Ausstattung:  

- [ ] Airbags
     - [ ] Fahrer
     - [ ] Beifahrer
   
- [ ] Klimaanlage
- [ ] Isofix-Base
- [ ]  Kindersitz
     - [ ]  Kindersitz
     - [ ]  Sitzerhöhung

- [ ] Zentralverriegelung
- [ ] Einparkhilfe 
      - [x] vorne 
      - [x] hinten 
      - [ ] 360°

- [ ]  universelle Handyhalterung
- [ ] Freisprecheinrichtung
- [ ]  internes Navigationssystem
- [ ]  Bluetooth-Radio
- [ ]  Becherhalter
- [ ]  USB Anschluss
- [ ]  Dachträger
- [ ]  Gepäckbox Dach
- [ ]  Fahrradträger 
     - [ ] Dach
     - [ ]  hinten
- [ ]  Ladegurte
- [ ] Anhängerkupplung

Freifeld Text - Sonstiges

**Comment by kerstin-m** [comment]
@danielkull @StefanH87 @kiraGit67  das sind die wichtigsten Details- für alles weitere reicht das Freifeld nehmen. Mit der Liste einverstanden? Dann über den Daumen bitte freigeben

**Comment by danielkull** [comment]
Der Fragebogen 

![Image](https://github.com/danielkull/capp/assets/119632155/9722851e-668c-41aa-8140-11f641d41746)

 und


![Image](https://github.com/danielkull/capp/assets/119632155/2b55d8ad-e683-4f25-8deb-3b66bd62c630)

soll die Daten abfragen die in diesem Fenster genutzt werden solen:


![Image](https://github.com/danielkull/capp/assets/119632155/a51cf725-2c63-4854-9325-850ff55ee2e4)
