### ISSUE TITLE
create passwort toggle

### ISSUE THREAD

**Issue by StefanH87** [danielkull/capp#40]
- button wurde in der Komponente inder LogView.vue eingebudnen
- Zeile 129

- mit JS PW Toogle um zwischen stext/passwort zu wechslen

![Image](https://user-images.githubusercontent.com/120994075/249314710-de4278a8-4157-4f33-880f-95f175e4e4bd.png)

**Comment by danielkull** [comment]
Habs umgesetzt. Baue es demnächst noch als Teil der InputText.vue Componente ein. Damit diese Funktionalität überall wo das Element mit dem Passenden Typ eingesetzt wird angewendet wird

**Comment by danielkull** [comment]
Folgende Punkte wurden umgesetzt:

- [ ] Wenn das Input Element den Type Password hat, wird das Augensymbol angezeigt, ansonsten nicht
- [ ] Beim klicken auf das Augensymbol wird gewechselt zwischen Password Sichtbar oder versteckt
- [ ] Der Style von dem Icon sowie die Funktionalität befinden sich jetzt _nicht mehr_ in der LogView.vue Komponente, sonddern in der **InputText.vue** Komponente
- [ ] Die **InputText.vue** Komponente hat nun einen Validator. Dieser Prüft ob die Komponente geladen wird mit den erlaubten Typen. Z.B. wenn <InputText :inputType="'button'" /> eingegeben wird, dann gibt es eine Warnmeldung. Da die Komponente zum jetzigen Standpunkt nur für text, email und password optimiert worden ist.
