### ISSUE TITLE
function for elements

### ISSUE THREAD

**Issue by StefanH87** [danielkull/capp#41]
-help buttons wurden erstellt und dazu gehörige Hilfstextfelder (Toggle effekt auf klick)
-invalid state text wurde eingebunden
- innherlab der eigenen komponente in der Input Componente
- mit Lgo In Button soll die 2. seite "Log In" von unten nach oben geschoben werden, Testweise wurde sie nach links verschoben

![Image](https://user-images.githubusercontent.com/120994075/249315028-fea46d08-aed7-4db9-953a-4248606c2697.png)

**Comment by StefanH87** [comment]
e. seite mit den Input fields nach links verschoben


![Image](https://github.com/danielkull/capp/assets/120994075/921c853b-2ae3-4b80-9bb5-8e8b772e94e4)

**Comment by danielkull** [comment]
Info: Werde mit dem Issue bald Anfangen

**Comment by danielkull** [comment]
- [ ] Helper Button in InputText.vue Componente eingebunden. Reagiert flexibel auf den gewählten Typ der InputText.vue Componente
- [ ] Invalid Status in InputText.vue Componente eingebunden. Reagiert flexibel auf den gewählten Typ der InputText.vue Componente
- [ ] Slider Animation eingefügt
- [ ] Neue Section für Sign In eingefügt (Ist noch im Draft)
- [ ] Slider Wechsel hin/zurück zwischen allen drei Pages funktioniert

Note: Neues Issue muss noch eröffnet werden bzgl. Responsive Design und vor allem das in der Mobile Ansicht sich das Design nicht verzieht.
