### ISSUE TITLE
Erste Aufgabe: Alle mit dem Board, der Vorgehensweise einverstanden? Dann Daumen hoch! Das Board ist eine blöde Idee? Dann bitte kommentieren:-)

### ISSUE THREAD

**Issue by kerstin-m** [danielkull/capp#44]

**Comment by kiraGit67** [comment]
Eine sehr gute Idee! Neue Ideen müssen unter uns diskutiert und so abgestimmt werden, dass wir alle "damit gut leben" können. Nur sollten wir dabei darauf achten,  dass wir uns nicht an einem bestimmten Punkt "fest diskutieren" und uns sogar verrennen. Am besten wäre es, gemeinsam für jede Idee Pro's und Contra's festzulegen und gegeneinander abzuwägen.

**Comment by kerstin-m** [comment]
@kiraGit67 : Haste recht, hab die description angepasst. Wir wollen ja nicht nur diskutieren, sondern auch reine Sachfragen klären🙃
