### ISSUE TITLE
Prüfen auf Merge Konflikte

### ISSUE THREAD

**Issue by kerstin-m** [danielkull/capp#49]
## Vorraussetzung:
- Als erstes: Install git graph in vscode extensions:

![Image](https://github.com/danielkull/capp/assets/119632155/7a93b7d9-3b4e-44c8-a4e1-f881ab0508ff)

## Bringe den Main auf den aktuellen stand

- Checkout zu main (davor muss du evtl. deinen laufenden Branch commiten)

![Image](https://github.com/danielkull/capp/assets/119632155/958417b8-9ba2-4036-99cc-63f5b0d6d7db)

- git fetch oder git fetch origin (In unserem Fall gibt es gerade kein Unterschied)

![Image](https://github.com/danielkull/capp/assets/119632155/54987228-d255-493e-a984-81268c852b3a)

- git pull

![Image](https://github.com/danielkull/capp/assets/119632155/54e728a5-d50b-43da-92c6-7eab4ee5d492)

- Checkout wieder zurück auf dem Branch den ihr testen wollt auf Merge Konflikte, damit dieser ohne Probleme gemerged werden kann.

![Image](https://github.com/danielkull/capp/assets/119632155/e08327af-d55e-4ff3-a959-714e0a51c76a)

- code . (Startet VSCode)

- clickt auf "Git Graph" unten in der Fußleiste um es zu öffnen

![Image](https://github.com/danielkull/capp/assets/119632155/95830daf-5587-47a6-8cc7-94e1a5def8c6)

- Hier wird der gesamte Baum von all unseren Commits, merges, branches ect. angezeigt.
- Im Beispiel sind wir hier ausgecheckt auf dem Branch "41-function-for-elements"
- Unser branch ist schon eine ziemliche weile weg vom main branch (siehe Roter Kasten mit Pfeil unten links)
- Wir wollen jetzt wieder beide zusammenführen. Da der Main branch neues hat wollen wir testen ob diese auch ohne Konflikte in unseren jetzigen Branch gemerged werden können.
- Wenn das nicht so ohne weiteres geht, dann gibt es "Merge Konflikte" die können wir gleich hier lösen, damit später der Reviewer sich nur auf den Review konzentrieren kann.

![Image](https://github.com/danielkull/capp/assets/119632155/775308de-61a8-4f23-ab6d-603cf0320b03)

- Wir machen einen rechts Klick auf den "main | origin" branch und wählen dann aus "Merge into current branch..."
- Der Current branch ist "41-function-for-elements"

![Image](https://github.com/danielkull/capp/assets/119632155/e467fbc8-bd77-44d5-9c19-bbf8834a22f8)

- Jetzt bestätigen wir das nächste Fenster. Prüfe noch das die Checkbox "Create a new commit even if fast-forward is possible" aktiviert ist. Wir wollen ja das in einem separaten Commit durchführen zur Sicherheit.

![Image](https://github.com/danielkull/capp/assets/119632155/c44546c1-256a-4405-9646-d7da05699602)

- Wenn kein Konflikt auftritt, dann kann man ohne Probleme, den branch pushen und in unserem Git Hub ein Pull request starten falls gewünscht.

- In unserem Fall haben wir aber ein Konflikt in der src/views/LogView.vue, die git leider nicht automatisch lösen kann.
- Git bittet uns um Hilfe, und da wir Freundlich sind helfen wir ❤

![Image](https://github.com/danielkull/capp/assets/119632155/49541ac9-4536-4314-b49a-9e67bd05c4da)

- Die betreffenden werden im Explorer von VSCode Rot angezeigt

![Image](https://github.com/danielkull/capp/assets/119632155/6b5a7e61-dcf3-4fc0-b3eb-a9dbff7aa7a0)

- Konflikte können auf unterschiedliche Weiße gelöst werden, daher hier ein Video

Hilfsvideo (von Sarah):
[Merge Konflikt](https://www.youtube.com/watch?v=lz5OuKzvadQ)

- In meinem Fall habe ich mich für den "Merge Editor entschieden"

![Image](https://github.com/danielkull/capp/assets/119632155/65351434-8e8c-4694-9fa3-bce070077862)

- Der zeigt oben links die "Incoming" Änderungen, also alles was vom "main" in unserem Branch kommt.
- Rechts oben ist der "Current" Status. Also alles was in unserem jetzigen Branch ist und ein Konflikt mit den Incoming hat.
- Unten gibt es eine Vorschau auf die "Results" wie es nach unserer Entscheidung aussieht.
- Die Entscheidungen befinden sich in diesen Gelben Kästchen und sind:
  - Accept Incoming
  - Accept Current
  - Accept Combination
  - Ignore
- Nach dem ihr alle Konflikte gelöst habe 👭, könnt ihr rechts unten den Complete Merge Button drücken um den Merge abzuschließen.

![Image](https://github.com/danielkull/capp/assets/119632155/0e494014-9037-4518-8d40-8b0a6fc77979)

- Nach dem Lösen der Konflikte kann man wie gewohnt commiten (es wird auch einem ein default text angeboten den man nehmen kann) und dann pushen --> pull request

Als Visualisierungs-Stütze hier ein Schematisches Bild:

![Image](https://github.com/danielkull/capp/assets/119632155/69752289-ebec-4f79-98fe-3ea25cb2c225)

**Comment by danielkull** [comment]
Fragen/Anregungen bitte hier im Chat reinschreiben 🙏

**Comment by kerstin-m** [comment]
Oder auch Lob? Danke für die umfangreiche Beschreibung:-)!
