### ISSUE TITLE
add icons

### ISSUE THREAD

**Issue by StefanH87** [danielkull/capp#5]
- selbst erstellenten Icons einbinden

**Comment by danielkull** [comment]
Stefan, wurde hier eigentlich schon etwas auf dem Branch gemacht?
Wenn nicht, oder falls es so wenig ist das man das auch ohne Probleme Kopieren kann. Dann würde ich lieber die Icons, in einem anderen Branch machen und den hier schließen.

Der Grund ist, das wir demnächst ziemlich weit sind und der Branch noch sehr vom beginn ist.
Andererseits, wenn du die icons in einem komplett anderen Teil einfügst und die anderen Dateien überhaupt nicht betroffen sind, dann kann man das noch machen.

Was meinst du?
