### ISSUE TITLE
commentar section in UsersProfile

### ISSUE THREAD

**Issue by kerstin-m** [danielkull/capp#51]
![Image](https://user-images.githubusercontent.com/120994075/248906293-fa7173c3-f573-4a31-ba3f-43e9a0d4b5fc.png)

- [x]  Componente erstellen
- [ ] textfield ntuzen

- [x] Platzhalter für die Icons verwenden bis zur Finalen wahl

**Comment by danielkull** [comment]
Hier wäre noch gut zu wissen, wo wir die Info Text mit Bewertung speichern. Den im Moment haben wir kein Backend Bereich dafür. Heißt die sind nur Lokal für den User verfügbar und niemand sieht das von einem anderen.
