### ISSUE TITLE
Einschränkungen zur Vermietung

### ISSUE THREAD

**Issue by danielkull** [danielkull/capp#59]
Was haltet ihr hiervon? Dann ist der Punkt "Ausstattung" sauber, aber wir brauchen eine neue Karteikarte, auf der wir das hier ausgefüllt werden kann

![Image](https://user-images.githubusercontent.com/120080320/250011859-3bb619ea-de3f-4932-a1ea-330b04c4f303.png)

**Comment by danielkull** [comment]
Finde ich gut. Das würde die App für den User auf jeden Fall übersichtlicher gestallten. 
Änderungen an unseren Code müssen wir sowieso bis zum Schluss noch durchführen.

**Comment by StefanH87** [comment]
Gute Idee , können dazu im Fragebogen ja nen extra Reiter machen da wird
das bisl übersichtlicher

Daniel Kull ***@***.***> schrieb am Fr. 30. Juni 2023 um
08:47:

**Comment by StefanH87** [comment]
Mindestalter wäre 18 oder ? XD

Stefan Hiob ***@***.***> schrieb am Fr. 30. Juni 2023 um
09:15:

**Comment by kiraGit67** [comment]
Einschränkungen zur Vermietung

Gibt es Einschränkungen für die Vermietung Deines Autos? - Dann kannst Du sie hier auswählen:

Mindestalter: 3 Stufen

- [ ] 18 Jahre
- [ ] 21 Jahre
- [ ] 25 Jahre
