### ISSUE TITLE
Einarbeitung in supabase Login

### ISSUE THREAD

**Issue by kiraGit67** [danielkull/capp#81]
- [ ]

**Comment by smaerdian-cbe** [comment]
https://supabase.com/docs/guides/auth

**Comment by kerstin-m** [comment]
Vielleicht hilft das: https://docs.google.com/document/d/1PZIpqKZaXanzHQuK5GfebJqXgQKpsu77c4D43DI_IP4/edit

**Comment by danielkull** [comment]
Habe das jetzt mal zu Information geschoben, da es sich hierbei hauptsächlich um Infos handelt und nicht direkt ein Arbeitsauftrag ausformuliert ist.
