### ISSUE TITLE
Option zur Erfassung neuer Autos

### ISSUE THREAD

**Issue by kiraGit67** [danielkull/capp#83]
Daniel: Die Erfassung von einem neuen Auto würde ich eigentlich an den Fragebogen koppeln. Da hier ja ein User die ganzen Infos über sein Auto angibt und mit dem Abschicken zum Owner wird. Das Auto wird ja dann auch in Supabase ihm zugewiesen.
Für den Normalen "Nutzer" User, würde ich nur den "Persönlichen Angaben" Bereich nutzen, da dieser ja kein Auto anmelden möchte. Dafür sollten aber seine Daten auch zum Profil zugeordnet werden.
Die Features würde ich nur im Backend verwalten. Wenn jeder User die Möglichkeit hätte Features zu erstellen die andere Sehen, dann wird daraus sehr schnell ein Selbst Läufer für Unfug.

**Comment by kerstin-m** [comment]
- [ ] neue Komponente (Formular) zur Erfassung neuer Autos
- [ ] Verlinkungen erstellen (Fragebogen)
