### ISSUE TITLE
FAQ

### ISSUE THREAD

**Issue by danielkull** [danielkull/capp#90]
Kerstin: Zu 90% fertig- überfliegt mal kurz, ob euch der Stil gefällt oder wesentliche Punkte fehlen. 
https://docs.google.com/document/d/1tpw9iQPWQAbZOua9ZMo49OQSBfVkwy15lzI0gT8xWe0/edit#heading=h.mebh9u56yi7u

**Comment by danielkull** [comment]
Finde ich gut. Habe noch ein paar Typos die ich gesehen habe gelöst. Mir gefällt der Schreibstyle 🙂. Muss mir noch die Tage Gedanken machen ob mir noch weitere FAQ einfallen, die man klären könnte.

**Comment by StefanH87** [comment]
find eich gut auch das mit dem DU
