### ISSUE TITLE
create componente "InputSelect"

### ISSUE THREAD

**Issue by kerstin-m** [danielkull/capp#94]

**Comment by StefanH87** [comment]
was ist hiermit genau gemeint ?

**Comment by danielkull** [comment]
Meist du damit das HTML <select> Tag für die Dropdown liste. Damit man das als funktionale Komponente für die enum Type Felder benutzen kann? Das hätten wir nämlich wirklich noch nicht.

**Comment by danielkull** [comment]
Wir haben mittlerweile eine Komponente die das select element abbildet "SelectDropDown.vue".
Würde daher das Issue schließen.
