### ISSUE TITLE
Loading Screen und State von Daten auf Null

### ISSUE THREAD

**Issue by danielkull** [danielkull/capp#99]
Hallo zusammen,
Kirsten hatte gerade ein Fall bei dem wir ein Fehler hatten, weil die Daten zum Fetchen von Supabase, länger gebraucht haben. In dem Fall waren es Daten auf einem weiteren unteren Level. Das hat zu einem Fehler geführt, da die Daten von dem Oberen Level noch nicht da waren und somit nichts (also auch nicht undefind) existiert hat.

Gabriel hat uns als Lösung vorgeschlagen, das wir beim State von den Daten diese auf Null setzten, und bei dem template Komponenten den Bereich mit v-if nach dem jeweiligen State truthiness fragen. Dazu vielleicht einen Loading screen (Könnte ein Issue werden) mit v-else. Der Angezeigt wird wenn die Hauptdaten noch am Laden sind.

**Comment by kiraGit67** [comment]
Sehr gute Idee!
